# Generated by Django 5.0.6 on 2024-05-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gaming_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
