# Generated by Django 5.0.6 on 2024-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_profile_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="thumbnail",
            field=models.ImageField(
                default="default-thumbnail.jpg", upload_to="thumbnails/"
            ),
        ),
    ]
