# Generated by Django 5.0.6 on 2024-06-03 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0006_alter_profile_last_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="last_activity",
        ),
    ]
