# Generated by Django 5.0.6 on 2024-06-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0007_remove_profile_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
